//Source code generated by AppGPT (www.appgpt.tech)
//to be autogenerated as template, one per resource
import { Entity, Column, PrimaryGeneratedColumn } from 'typeorm';

@Entity('Expenses')
export class ExpensesEntity {
  @PrimaryGeneratedColumn()
  id: number;

  @Column('integer', { nullable: true })
  ExpenseID: number;

  @Column('date', { nullable: true })
  DateAndTime: Date;

  @Column('real', { nullable: true })
  Amount: number;

  @Column('text', { nullable: true })
  Category: string;

  @Column('text', { nullable: true })
  Description: string;

  @Column('text', { nullable: true })
  PaymentMethod: string;

  @Column('text', { nullable: true })
  PurchaseLocation: string;

  @Column('text', { nullable: true })
  Recipient: string;

  @Column('text', { nullable: true })
  Status: string;

  @Column('text', { nullable: true })
  ReceiptPhotoScan: string;

  @Column('text', { nullable: true })
  Recurrence: string;

  @Column('text', { nullable: true })
  Currency: string;

  @Column('integer', { nullable: true })
  User: number;

  @Column('text', { nullable: true })
  ProjectGoal: string;
}
