//Source code generated by AppGPT (www.appgpt.tech)
//to be autogenerated as template, one per resource
import { Entity, Column, PrimaryGeneratedColumn } from 'typeorm';

@Entity('Incomes')
export class IncomesEntity {
  @PrimaryGeneratedColumn()
  id: number;

  @Column('integer', { nullable: true })
  IncomeID: number;

  @Column('date', { nullable: true })
  DateAndTime: Date;

  @Column('real', { nullable: true })
  Amount: number;

  @Column('text', { nullable: true })
  Source: string;

  @Column('text', { nullable: true })
  Description: string;

  @Column('text', { nullable: true })
  IncomeType: string;

  @Column('text', { nullable: true })
  Status: string;

  @Column('text', { nullable: true })
  PaymentMethod: string;

  @Column('text', { nullable: true })
  Investment: string;

  @Column('real', { nullable: true })
  Taxes: number;

  @Column('integer', { nullable: true })
  User: number;

  @Column('text', { nullable: true })
  Recurrence: string;

  @Column('text', { nullable: true })
  Currency: string;

  @Column('text', { nullable: true })
  ProjectOrGoal: string;
}
