//Source code generated by AppGPT (www.appgpt.tech)
//to be autogenerated as template, one per resource
import { Entity, Column, PrimaryGeneratedColumn } from 'typeorm';

@Entity('Notes')
export class NotesEntity {
  @PrimaryGeneratedColumn()
  id: number;

  @Column('integer', { nullable: true })
  noteId: number;

  @Column('text', { nullable: true })
  title: string;

  @Column('text', { nullable: true })
  content: string;

  @Column('date', { nullable: true })
  creationDate: Date;

  @Column('integer', { nullable: true })
  categoryId: number;

  @Column('text', { nullable: true })
  priority: string;

  @Column('date', { nullable: true })
  reminder: Date;
}
