//Source code generated by AppGPT (www.appgpt.tech)
//to be autogenerated as template, one per resource
import { Entity, Column, PrimaryGeneratedColumn } from 'typeorm';

@Entity('Reminders')
export class RemindersEntity {
  @PrimaryGeneratedColumn()
  id: number;

  @Column('integer', { nullable: true })
  ReminderID: number;

  @Column('text', { nullable: true })
  Title: string;

  @Column('text', { nullable: true })
  Description: string;

  @Column('date', { nullable: true })
  DateAndTime: Date;

  @Column('text', { nullable: true })
  Recurrence: string;

  @Column('text', { nullable: true })
  Priority: string;

  @Column('text', { nullable: true })
  Category: string;

  @Column('text', { nullable: true })
  RelatedIndividuals: string;

  @Column('text', { nullable: true })
  Location: string;

  @Column('text', { nullable: true })
  Status: string;

  @Column('text', { nullable: true })
  Notifications: string;

  @Column('text', { nullable: true })
  ColorLabel: string;

  @Column('text', { nullable: true })
  Attachments: string;

  @Column('text', { nullable: true })
  Creator: string;

  @Column('text', { nullable: true })
  AdditionalNotes: string;
}
