//Source code generated by AppGPT (www.appgpt.tech)
//to be autogenerated as template, one per resource
import { Entity, Column, PrimaryGeneratedColumn } from 'typeorm';

@Entity('Reports')
export class ReportsEntity {
  @PrimaryGeneratedColumn()
  id: number;

  @Column('integer', { nullable: true })
  ReportID: number;

  @Column('date', { nullable: true })
  CreationDate: Date;

  @Column('text', { nullable: true })
  ReportType: string;

  @Column('text', { nullable: true })
  Period: string;

  @Column('text', { nullable: true })
  Author: string;

  @Column('text', { nullable: true })
  ReportPurpose: string;

  @Column('text', { nullable: true })
  Description: string;

  @Column('text', { nullable: true })
  ReportData: string;

  @Column('text', { nullable: true })
  ReportStatus: string;

  @Column('text', { nullable: true })
  Recipient: string;

  @Column('text', { nullable: true })
  FilesAndAttachments: string;

  @Column('text', { nullable: true })
  CommentsAndRemarks: string;

  @Column('text', { nullable: true })
  MethodsAndSourcesUsed: string;

  @Column('text', { nullable: true })
  SummaryOrConclusions: string;

  @Column('text', { nullable: true })
  SignatureAndApproval: string;
}
