//Source code generated by AppGPT (www.appgpt.tech)
import {
  Datagrid,
  List,
  EditButton,
  Edit,
  SimpleForm,
  Create,
  SelectColumnsButton,
  DatagridConfigurable,
  TopToolbar,
  CreateButton,
  ExportButton,
  FilterButton,
  //Field controls
  BooleanField,
  DateField,
  EmailField,
  ImageField,
  NumberField,
  ReferenceField,
  TextField,
  UrlField,
  //Input controls
  BooleanInput,
  DateInput,
  EmailInput,
  ImageInput,
  NumberInput,
  ReferenceInput,
  TextInput,
  UrlInput,
  PasswordInput,
} from 'react-admin';
import { useRecordContext } from 'react-admin';
import { Grid } from '@mui/material';
const ReadOnlyPasswordField = ({ record, source }) => {
  // You can customize the way you display the password here, e.g., mask it with asterisks
  const maskedPassword = '********';

  return <span>{maskedPassword}</span>;
};
const ListActions = () => (
  <TopToolbar>
    <FilterButton />
    <CreateButton />
    <ExportButton />
    <SelectColumnsButton />
  </TopToolbar>
);
const RemindersTitle = () => {
  const record = useRecordContext();
  return <span>Reminders {record ? `"${record.Title}"` : ''}</span>;
};

export const RemindersList = () => (
  <List actions={<ListActions />} filters={ResourceFilters}>
    <DatagridConfigurable>
      <NumberField source="ReminderID" />
      <TextField source="Title" />
      <TextField source="Description" />
      <DateField source="DateAndTime" />
      <TextField source="Recurrence" />
      <TextField source="Priority" />
      <TextField source="Category" />
      <TextField source="RelatedIndividuals" />
      <TextField source="Location" />
      <TextField source="Status" />
      <TextField source="Notifications" />
      <TextField source="ColorLabel" />
      <TextField source="Attachments" />
      <TextField source="Creator" />
      <TextField source="AdditionalNotes" />
      <EditButton />
    </DatagridConfigurable>
  </List>
);

export const RemindersEdit = () => (
  <Edit title={<RemindersTitle />}>
    <SimpleForm>
      <Grid container rowSpacing={1} columnSpacing={{ xs: 1, sm: 2, md: 5 }}>
        <Grid item xs={4}>
          <NumberInput source="ReminderID" />
        </Grid>
        <Grid item xs={4}>
          <TextInput source="Title" />
        </Grid>
        <Grid item xs={4}>
          <TextInput source="Description" />
        </Grid>
        <Grid item xs={4}>
          <DateInput source="DateAndTime" />
        </Grid>
        <Grid item xs={4}>
          <TextInput source="Recurrence" />
        </Grid>
        <Grid item xs={4}>
          <TextInput source="Priority" />
        </Grid>
        <Grid item xs={4}>
          <TextInput source="Category" />
        </Grid>
        <Grid item xs={4}>
          <TextInput source="RelatedIndividuals" />
        </Grid>
        <Grid item xs={4}>
          <TextInput source="Location" />
        </Grid>
        <Grid item xs={4}>
          <TextInput source="Status" />
        </Grid>
        <Grid item xs={4}>
          <TextInput source="Notifications" />
        </Grid>
        <Grid item xs={4}>
          <TextInput source="ColorLabel" />
        </Grid>
        <Grid item xs={4}>
          <TextInput source="Attachments" />
        </Grid>
        <Grid item xs={4}>
          <TextInput source="Creator" />
        </Grid>
        <Grid item xs={4}>
          <TextInput source="AdditionalNotes" />
        </Grid>
      </Grid>
    </SimpleForm>
  </Edit>
);

export const RemindersCreate = () => (
  <Create>
    <SimpleForm>
      <Grid container rowSpacing={1} columnSpacing={{ xs: 1, sm: 2, md: 5 }}>
        <Grid item xs={4}>
          <NumberInput source="ReminderID" />
        </Grid>
        <Grid item xs={4}>
          <TextInput source="Title" />
        </Grid>
        <Grid item xs={4}>
          <TextInput source="Description" />
        </Grid>
        <Grid item xs={4}>
          <DateInput source="DateAndTime" />
        </Grid>
        <Grid item xs={4}>
          <TextInput source="Recurrence" />
        </Grid>
        <Grid item xs={4}>
          <TextInput source="Priority" />
        </Grid>
        <Grid item xs={4}>
          <TextInput source="Category" />
        </Grid>
        <Grid item xs={4}>
          <TextInput source="RelatedIndividuals" />
        </Grid>
        <Grid item xs={4}>
          <TextInput source="Location" />
        </Grid>
        <Grid item xs={4}>
          <TextInput source="Status" />
        </Grid>
        <Grid item xs={4}>
          <TextInput source="Notifications" />
        </Grid>
        <Grid item xs={4}>
          <TextInput source="ColorLabel" />
        </Grid>
        <Grid item xs={4}>
          <TextInput source="Attachments" />
        </Grid>
        <Grid item xs={4}>
          <TextInput source="Creator" />
        </Grid>
        <Grid item xs={4}>
          <TextInput source="AdditionalNotes" />
        </Grid>
      </Grid>
    </SimpleForm>
  </Create>
);

const ResourceFilters = [
  <TextInput source="q" label="Search" alwaysOn />,
  ,
  ,
  ,
  ,
  ,
  ,
  ,
  ,
  ,
  ,
  ,
  ,
  ,
  ,
  ,
];
