//Source code generated by AppGPT (www.appgpt.tech)
import {
  Datagrid,
  List,
  EditButton,
  Edit,
  SimpleForm,
  Create,
  SelectColumnsButton,
  DatagridConfigurable,
  TopToolbar,
  CreateButton,
  ExportButton,
  FilterButton,
  //Field controls
  BooleanField,
  DateField,
  EmailField,
  ImageField,
  NumberField,
  ReferenceField,
  TextField,
  UrlField,
  //Input controls
  BooleanInput,
  DateInput,
  EmailInput,
  ImageInput,
  NumberInput,
  ReferenceInput,
  TextInput,
  UrlInput,
  PasswordInput,
} from 'react-admin';
import { useRecordContext } from 'react-admin';
import { Grid } from '@mui/material';
const ReadOnlyPasswordField = ({ record, source }) => {
  // You can customize the way you display the password here, e.g., mask it with asterisks
  const maskedPassword = '********';

  return <span>{maskedPassword}</span>;
};
const ListActions = () => (
  <TopToolbar>
    <FilterButton />
    <CreateButton />
    <ExportButton />
    <SelectColumnsButton />
  </TopToolbar>
);
const ReportsTitle = () => {
  const record = useRecordContext();
  return <span>Reports {record ? `"${record.id}"` : ''}</span>;
};

export const ReportsList = () => (
  <List actions={<ListActions />} filters={ResourceFilters}>
    <DatagridConfigurable>
      <NumberField source="ReportID" />
      <DateField source="CreationDate" />
      <TextField source="ReportType" />
      <TextField source="Period" />
      <TextField source="Author" />
      <TextField source="ReportPurpose" />
      <TextField source="Description" />
      <TextField source="ReportData" />
      <TextField source="ReportStatus" />
      <TextField source="Recipient" />
      <TextField source="FilesAndAttachments" />
      <TextField source="CommentsAndRemarks" />
      <TextField source="MethodsAndSourcesUsed" />
      <TextField source="SummaryOrConclusions" />
      <TextField source="SignatureAndApproval" />
      <EditButton />
    </DatagridConfigurable>
  </List>
);

export const ReportsEdit = () => (
  <Edit title={<ReportsTitle />}>
    <SimpleForm>
      <Grid container rowSpacing={1} columnSpacing={{ xs: 1, sm: 2, md: 5 }}>
        <Grid item xs={4}>
          <NumberInput source="ReportID" />
        </Grid>
        <Grid item xs={4}>
          <DateInput source="CreationDate" />
        </Grid>
        <Grid item xs={4}>
          <TextInput source="ReportType" />
        </Grid>
        <Grid item xs={4}>
          <TextInput source="Period" />
        </Grid>
        <Grid item xs={4}>
          <TextInput source="Author" />
        </Grid>
        <Grid item xs={4}>
          <TextInput source="ReportPurpose" />
        </Grid>
        <Grid item xs={4}>
          <TextInput source="Description" />
        </Grid>
        <Grid item xs={4}>
          <TextInput source="ReportData" />
        </Grid>
        <Grid item xs={4}>
          <TextInput source="ReportStatus" />
        </Grid>
        <Grid item xs={4}>
          <TextInput source="Recipient" />
        </Grid>
        <Grid item xs={4}>
          <TextInput source="FilesAndAttachments" />
        </Grid>
        <Grid item xs={4}>
          <TextInput source="CommentsAndRemarks" />
        </Grid>
        <Grid item xs={4}>
          <TextInput source="MethodsAndSourcesUsed" />
        </Grid>
        <Grid item xs={4}>
          <TextInput source="SummaryOrConclusions" />
        </Grid>
        <Grid item xs={4}>
          <TextInput source="SignatureAndApproval" />
        </Grid>
      </Grid>
    </SimpleForm>
  </Edit>
);

export const ReportsCreate = () => (
  <Create>
    <SimpleForm>
      <Grid container rowSpacing={1} columnSpacing={{ xs: 1, sm: 2, md: 5 }}>
        <Grid item xs={4}>
          <NumberInput source="ReportID" />
        </Grid>
        <Grid item xs={4}>
          <DateInput source="CreationDate" />
        </Grid>
        <Grid item xs={4}>
          <TextInput source="ReportType" />
        </Grid>
        <Grid item xs={4}>
          <TextInput source="Period" />
        </Grid>
        <Grid item xs={4}>
          <TextInput source="Author" />
        </Grid>
        <Grid item xs={4}>
          <TextInput source="ReportPurpose" />
        </Grid>
        <Grid item xs={4}>
          <TextInput source="Description" />
        </Grid>
        <Grid item xs={4}>
          <TextInput source="ReportData" />
        </Grid>
        <Grid item xs={4}>
          <TextInput source="ReportStatus" />
        </Grid>
        <Grid item xs={4}>
          <TextInput source="Recipient" />
        </Grid>
        <Grid item xs={4}>
          <TextInput source="FilesAndAttachments" />
        </Grid>
        <Grid item xs={4}>
          <TextInput source="CommentsAndRemarks" />
        </Grid>
        <Grid item xs={4}>
          <TextInput source="MethodsAndSourcesUsed" />
        </Grid>
        <Grid item xs={4}>
          <TextInput source="SummaryOrConclusions" />
        </Grid>
        <Grid item xs={4}>
          <TextInput source="SignatureAndApproval" />
        </Grid>
      </Grid>
    </SimpleForm>
  </Create>
);

const ResourceFilters = [
  <TextInput source="q" label="Search" alwaysOn />,
  ,
  ,
  ,
  ,
  ,
  ,
  ,
  ,
  ,
  ,
  ,
  ,
  ,
  ,
  ,
];
