//Source code generated by AppGPT (www.appgpt.tech)
import {
  Datagrid,
  List,
  EditButton,
  Edit,
  SimpleForm,
  Create,
  SelectColumnsButton,
  DatagridConfigurable,
  TopToolbar,
  CreateButton,
  ExportButton,
  FilterButton,
  //Field controls
  BooleanField,
  DateField,
  EmailField,
  ImageField,
  NumberField,
  ReferenceField,
  TextField,
  UrlField,
  //Input controls
  BooleanInput,
  DateInput,
  EmailInput,
  ImageInput,
  NumberInput,
  ReferenceInput,
  TextInput,
  UrlInput,
  PasswordInput,
} from 'react-admin';
import { useRecordContext } from 'react-admin';
import { Grid } from '@mui/material';
const ReadOnlyPasswordField = ({ record, source }) => {
  // You can customize the way you display the password here, e.g., mask it with asterisks
  const maskedPassword = '********';

  return <span>{maskedPassword}</span>;
};
const ListActions = () => (
  <TopToolbar>
    <FilterButton />
    <CreateButton />
    <ExportButton />
    <SelectColumnsButton />
  </TopToolbar>
);
const TransactionsTitle = () => {
  const record = useRecordContext();
  return <span>Transactions {record ? `"${record.id}"` : ''}</span>;
};

export const TransactionsList = () => (
  <List actions={<ListActions />} filters={ResourceFilters}>
    <DatagridConfigurable>
      <NumberField source="TransactionID" />
      <DateField source="DateAndTime" />
      <NumberField source="Amount" />
      <TextField source="TransactionType" />
      <TextField source="TransactionStatus" />
      <TextField source="SenderAccount" />
      <TextField source="RecipientAccount" />
      <TextField source="Comment" />
      <TextField source="Category" />
      <TextField source="PaymentMethod" />
      <EditButton />
    </DatagridConfigurable>
  </List>
);

export const TransactionsEdit = () => (
  <Edit title={<TransactionsTitle />}>
    <SimpleForm>
      <Grid container rowSpacing={1} columnSpacing={{ xs: 1, sm: 2, md: 5 }}>
        <Grid item xs={4}>
          <NumberInput source="TransactionID" />
        </Grid>
        <Grid item xs={4}>
          <DateInput source="DateAndTime" />
        </Grid>
        <Grid item xs={4}>
          <NumberInput source="Amount" />
        </Grid>
        <Grid item xs={4}>
          <TextInput source="TransactionType" />
        </Grid>
        <Grid item xs={4}>
          <TextInput source="TransactionStatus" />
        </Grid>
        <Grid item xs={4}>
          <TextInput source="SenderAccount" />
        </Grid>
        <Grid item xs={4}>
          <TextInput source="RecipientAccount" />
        </Grid>
        <Grid item xs={4}>
          <TextInput source="Comment" />
        </Grid>
        <Grid item xs={4}>
          <TextInput source="Category" />
        </Grid>
        <Grid item xs={4}>
          <TextInput source="PaymentMethod" />
        </Grid>
      </Grid>
    </SimpleForm>
  </Edit>
);

export const TransactionsCreate = () => (
  <Create>
    <SimpleForm>
      <Grid container rowSpacing={1} columnSpacing={{ xs: 1, sm: 2, md: 5 }}>
        <Grid item xs={4}>
          <NumberInput source="TransactionID" />
        </Grid>
        <Grid item xs={4}>
          <DateInput source="DateAndTime" />
        </Grid>
        <Grid item xs={4}>
          <NumberInput source="Amount" />
        </Grid>
        <Grid item xs={4}>
          <TextInput source="TransactionType" />
        </Grid>
        <Grid item xs={4}>
          <TextInput source="TransactionStatus" />
        </Grid>
        <Grid item xs={4}>
          <TextInput source="SenderAccount" />
        </Grid>
        <Grid item xs={4}>
          <TextInput source="RecipientAccount" />
        </Grid>
        <Grid item xs={4}>
          <TextInput source="Comment" />
        </Grid>
        <Grid item xs={4}>
          <TextInput source="Category" />
        </Grid>
        <Grid item xs={4}>
          <TextInput source="PaymentMethod" />
        </Grid>
      </Grid>
    </SimpleForm>
  </Create>
);

const ResourceFilters = [
  <TextInput source="q" label="Search" alwaysOn />,
  ,
  ,
  ,
  ,
  ,
  ,
  ,
  ,
  ,
  ,
];
