//Source code generated by AppGPT (www.appgpt.tech)
import { Card, CardContent, CardHeader } from '@mui/material';
export const Dashboard = () => (
  <Card>
    <CardHeader title="PLAN B" />
    <CardContent>
      Это приложение предназначено для управления личными финансами и задачами,
      обеспечивая удобный доступ ко всей необходимой информации в одном месте.
      Приложение поможет отслеживать историю покупок, вести учет расходов и
      доходов, создавать отчеты, напоминать о важных событиях, управлять
      задачами с приоритетами и создавать заметки с возможностью их
      категоризации.
      <p>
        Built with{' '}
        <a
          href="https://www.appgpt.tech"
          target="_blank"
          rel="noopener noreferrer"
        >
          AppGPT
        </a>
      </p>
    </CardContent>
  </Card>
);
